### ISSUE TITLE
Including LICENSE file in the code repository

### ISSUE THREAD

**Issue by chkumar246** [testing-cabal/unittest-ext#96]
We are packaging python-discover for fedora. from the code repository and pypi tarball, LICENSE file is missing. Please include the license file in the code repository.

**Comment by rbtcollins** [comment]
This code repository is stale - it's an import from google code, current unittest2 code is on hg.python.org.

**Comment by rbtcollins** [comment]
Also, what is python-discover?

**Comment by chkumar246** [comment]
python-discover is the package name of discover python module : https://pypi.python.org/pypi/discover

**Comment by rbtcollins** [comment]
Discover is obsolete and not being updated or changed. Its not needed for anything on any supported (by upstream) version of Python. Why are you packaging it?

**Comment by chkumar246** [comment]
@rbtcollins It is used in openstack projects.

**Comment by rbtcollins** [comment]
No its not - I am one of the main maintainers of that testing tooling, and discover is not used.

**Comment by rbtcollins** [comment]
(why do you think its used?)

**Comment by chkumar246** [comment]
As per the test-requirements.txt, https://github.com/openstack/cinder/blob/master/test-requirements.txt it is used.

**Comment by rbtcollins** [comment]
Thats a bug. https://review.openstack.org/217046

**Comment by chkumar246** [comment]
@rbtcollins Can you create a bug to track this on launchpad?

**Comment by rbtcollins** [comment]
You can if you want to :) Its just a stale test dependency, nothing that affects users.
