### ISSUE TITLE
extras_require key breaks setup.py with older setuptools

### ISSUE THREAD

**Issue by mcepl** [testing-cabal/unittest-ext#98]
With RHEL-7 I have `python-setuptools 0.9.8-4` and it breaks:

```
# python setup.py build
error in unittest2 setup command: Invalid environment marker: python_version<="2.6"
#
```

I would think that this key of `setup()` command should go.

**Comment by rbtcollins** [comment]
We need that to handle python version differences, sorry - there are workarounds that can be used, but the best is to use a more recent setuptools: if you're installing unittest2 globally, upgrade setuptools globally. If you're installing in a virtualenv, upgrade setuptools in your virtualenv first. We could possibly version-check setuptools ourselves and throw an error, but we had pretty average results doing that with mock.

**Comment by mcepl** [comment]
Well, I hoped, that I could find here some help with #97 so I was willing to upgrade unittest to the `master` here. Apparently, I won't get any help, so I will have to create fix myself anyway, there is no reason not to patch RHEL package instead (yes, when if I find out something, I will provide patch here).
